# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platinumcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rssi', models.CharField(max_length=32)),
                ('mac_address', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('mac_address', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='division',
            name='league',
        ),
        migrations.RemoveField(
            model_name='team',
            name='club',
        ),
        migrations.RemoveField(
            model_name='team',
            name='division',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='League',
        ),
    ]
